
package servicios;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-11-19T12:41:13.468-03:00
 * Generated source version: 3.2.6
 *
 */
public final class Publicador_PublicadorPort_Client {

    private static final QName SERVICE_NAME = new QName("http://servicios/", "PublicadorService");

    private Publicador_PublicadorPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PublicadorService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        PublicadorService ss = new PublicadorService(wsdlURL, SERVICE_NAME);
        Publicador port = ss.getPublicadorPort();

        {
        System.out.println("Invoking getDtVideosPropietario...");
        java.lang.String _getDtVideosPropietario_arg0 = "_getDtVideosPropietario_arg0-1258120583";
        servicios.DtPaquete _getDtVideosPropietario__return = port.getDtVideosPropietario(_getDtVideosPropietario_arg0);
        System.out.println("getDtVideosPropietario.result=" + _getDtVideosPropietario__return);


        }
        {
        System.out.println("Invoking getDtVideo...");
        int _getDtVideo_arg0 = 1667574235;
        servicios.DtPaquete _getDtVideo__return = port.getDtVideo(_getDtVideo_arg0);
        System.out.println("getDtVideo.result=" + _getDtVideo__return);


        }
        {
        System.out.println("Invoking getDtListasPrivadasUsuario...");
        java.lang.String _getDtListasPrivadasUsuario_arg0 = "_getDtListasPrivadasUsuario_arg0866568275";
        servicios.DtPaquete _getDtListasPrivadasUsuario__return = port.getDtListasPrivadasUsuario(_getDtListasPrivadasUsuario_arg0);
        System.out.println("getDtListasPrivadasUsuario.result=" + _getDtListasPrivadasUsuario__return);


        }
        {
        System.out.println("Invoking getDtListasParticularesPublicasUsuario...");
        java.lang.String _getDtListasParticularesPublicasUsuario_arg0 = "_getDtListasParticularesPublicasUsuario_arg0-652881044";
        servicios.DtPaquete _getDtListasParticularesPublicasUsuario__return = port.getDtListasParticularesPublicasUsuario(_getDtListasParticularesPublicasUsuario_arg0);
        System.out.println("getDtListasParticularesPublicasUsuario.result=" + _getDtListasParticularesPublicasUsuario__return);


        }
        {
        System.out.println("Invoking listarNombresUsuarios...");
        servicios.DtPaquete _listarNombresUsuarios__return = port.listarNombresUsuarios();
        System.out.println("listarNombresUsuarios.result=" + _listarNombresUsuarios__return);


        }
        {
        System.out.println("Invoking getDtVideosPublicos...");
        java.lang.String _getDtVideosPublicos_arg0 = "_getDtVideosPublicos_arg0-1349838200";
        servicios.DtPaquete _getDtVideosPublicos__return = port.getDtVideosPublicos(_getDtVideosPublicos_arg0);
        System.out.println("getDtVideosPublicos.result=" + _getDtVideosPublicos__return);


        }
        {
        System.out.println("Invoking listarCategorias...");
        servicios.DtPaquete _listarCategorias__return = port.listarCategorias();
        System.out.println("listarCategorias.result=" + _listarCategorias__return);


        }
        {
        System.out.println("Invoking altaListaParticular...");
        java.lang.String _altaListaParticular_arg0 = "_altaListaParticular_arg0-1471863060";
        java.lang.String _altaListaParticular_arg1 = "_altaListaParticular_arg11094718633";
        boolean _altaListaParticular_arg2 = true;
        try {
            port.altaListaParticular(_altaListaParticular_arg0, _altaListaParticular_arg1, _altaListaParticular_arg2);

        } catch (DuplicateClassException_Exception e) {
            System.out.println("Expected exception: DuplicateClassException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaVideo...");
        java.lang.String _consultaVideo_arg0 = "_consultaVideo_arg01342045512";
        int _consultaVideo_arg1 = 2021390293;
        try {
            port.consultaVideo(_consultaVideo_arg0, _consultaVideo_arg1);

        } catch (NotFoundException_Exception e) {
            System.out.println("Expected exception: NotFoundException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getImagen...");
        java.lang.String _getImagen_arg0 = "_getImagen_arg0708946840";
        byte[] _getImagen__return = port.getImagen(_getImagen_arg0);
        System.out.println("getImagen.result=" + _getImagen__return);


        }
        {
        System.out.println("Invoking getListasPublicas...");
        servicios.DtPaquete _getListasPublicas__return = port.getListasPublicas();
        System.out.println("getListasPublicas.result=" + _getListasPublicas__return);


        }
        {
        System.out.println("Invoking busquedaVideo...");
        java.lang.String _busquedaVideo_arg0 = "_busquedaVideo_arg01707822043";
        int _busquedaVideo_arg1 = 1890656093;
        servicios.DtPaquete _busquedaVideo__return = port.busquedaVideo(_busquedaVideo_arg0, _busquedaVideo_arg1);
        System.out.println("busquedaVideo.result=" + _busquedaVideo__return);


        }
        {
        System.out.println("Invoking cargarDatos...");
        port.cargarDatos();


        }
        {
        System.out.println("Invoking getDtLista...");
        int _getDtLista_arg0 = -1607132239;
        servicios.DtPaquete _getDtLista__return = port.getDtLista(_getDtLista_arg0);
        System.out.println("getDtLista.result=" + _getDtLista__return);


        }
        {
        System.out.println("Invoking seguir...");
        java.lang.String _seguir_arg0 = "_seguir_arg0-1892084627";
        java.lang.String _seguir_arg1 = "_seguir_arg11374953134";
        port.seguir(_seguir_arg0, _seguir_arg1);


        }
        {
        System.out.println("Invoking busquedaGeneral...");
        java.lang.String _busquedaGeneral_arg0 = "_busquedaGeneral_arg01631426637";
        int _busquedaGeneral_arg1 = -1584010927;
        servicios.DtPaquete _busquedaGeneral__return = port.busquedaGeneral(_busquedaGeneral_arg0, _busquedaGeneral_arg1);
        System.out.println("busquedaGeneral.result=" + _busquedaGeneral__return);


        }
        {
        System.out.println("Invoking getListaPublicoDtVideo...");
        servicios.DtPaquete _getListaPublicoDtVideo__return = port.getListaPublicoDtVideo();
        System.out.println("getListaPublicoDtVideo.result=" + _getListaPublicoDtVideo__return);


        }
        {
        System.out.println("Invoking borrarUsuario...");
        java.lang.String _borrarUsuario_arg0 = "_borrarUsuario_arg01837866936";
        try {
            port.borrarUsuario(_borrarUsuario_arg0);

        } catch (NotFoundException_Exception e) {
            System.out.println("Expected exception: NotFoundException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking existeNick...");
        java.lang.String _existeNick_arg0 = "_existeNick_arg01304021826";
        boolean _existeNick__return = port.existeNick(_existeNick_arg0);
        System.out.println("existeNick.result=" + _existeNick__return);


        }
        {
        System.out.println("Invoking valorarVideo...");
        java.lang.String _valorarVideo_arg0 = "_valorarVideo_arg0-464354546";
        boolean _valorarVideo_arg1 = false;
        java.lang.String _valorarVideo_arg2 = "_valorarVideo_arg2-1103072262";
        java.lang.String _valorarVideo_arg3 = "_valorarVideo_arg31265249929";
        port.valorarVideo(_valorarVideo_arg0, _valorarVideo_arg1, _valorarVideo_arg2, _valorarVideo_arg3);


        }
        {
        System.out.println("Invoking listarListasDefectoUsuario...");
        java.lang.String _listarListasDefectoUsuario_arg0 = "_listarListasDefectoUsuario_arg0-2003616807";
        servicios.DtPaquete _listarListasDefectoUsuario__return = port.listarListasDefectoUsuario(_listarListasDefectoUsuario_arg0);
        System.out.println("listarListasDefectoUsuario.result=" + _listarListasDefectoUsuario__return);


        }
        {
        System.out.println("Invoking altaUsuario...");
        java.lang.String _altaUsuario_arg0 = "_altaUsuario_arg0-1571309066";
        java.lang.String _altaUsuario_arg1 = "_altaUsuario_arg1-686673507";
        java.lang.String _altaUsuario_arg2 = "_altaUsuario_arg2536006763";
        java.lang.String _altaUsuario_arg3 = "_altaUsuario_arg3884680516";
        javax.xml.datatype.XMLGregorianCalendar _altaUsuario_arg4 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-11-19T12:41:13.530-03:00");
        byte[] _altaUsuario_imagen = new byte[] {};
        java.lang.String _altaUsuario_arg6 = "_altaUsuario_arg61882757509";
        java.lang.String _altaUsuario_arg7 = "_altaUsuario_arg740002083";
        java.lang.String _altaUsuario_arg8 = "_altaUsuario_arg8-2023754518";
        boolean _altaUsuario_arg9 = false;
        java.lang.String _altaUsuario_arg10 = "_altaUsuario_arg10-275642576";
        port.altaUsuario(_altaUsuario_arg0, _altaUsuario_arg1, _altaUsuario_arg2, _altaUsuario_arg3, _altaUsuario_arg4, _altaUsuario_imagen, _altaUsuario_arg6, _altaUsuario_arg7, _altaUsuario_arg8, _altaUsuario_arg9, _altaUsuario_arg10);


        }
        {
        System.out.println("Invoking existeLista...");
        java.lang.String _existeLista_arg0 = "_existeLista_arg0899163810";
        java.lang.String _existeLista_arg1 = "_existeLista_arg11188633479";
        boolean _existeLista__return = port.existeLista(_existeLista_arg0, _existeLista_arg1);
        System.out.println("existeLista.result=" + _existeLista__return);


        }
        {
        System.out.println("Invoking modificarVideo...");
        java.lang.String _modificarVideo_arg0 = "_modificarVideo_arg0-289432259";
        java.lang.String _modificarVideo_arg1 = "_modificarVideo_arg1520606345";
        java.lang.String _modificarVideo_arg2 = "_modificarVideo_arg2941021551";
        java.lang.String _modificarVideo_arg3 = "_modificarVideo_arg3-2099539740";
        java.lang.String _modificarVideo_arg4 = "_modificarVideo_arg41080683494";
        java.lang.String _modificarVideo_arg5 = "_modificarVideo_arg51934247086";
        long _modificarVideo_arg6 = 3931808610360358570l;
        boolean _modificarVideo_arg7 = true;
        javax.xml.datatype.XMLGregorianCalendar _modificarVideo_arg8 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-11-19T12:41:13.534-03:00");
        port.modificarVideo(_modificarVideo_arg0, _modificarVideo_arg1, _modificarVideo_arg2, _modificarVideo_arg3, _modificarVideo_arg4, _modificarVideo_arg5, _modificarVideo_arg6, _modificarVideo_arg7, _modificarVideo_arg8);


        }
        {
        System.out.println("Invoking busquedaCanales...");
        java.lang.String _busquedaCanales_arg0 = "_busquedaCanales_arg0-1361853237";
        int _busquedaCanales_arg1 = 574874265;
        servicios.DtPaquete _busquedaCanales__return = port.busquedaCanales(_busquedaCanales_arg0, _busquedaCanales_arg1);
        System.out.println("busquedaCanales.result=" + _busquedaCanales__return);


        }
        {
        System.out.println("Invoking altaVideo...");
        java.lang.String _altaVideo_arg0 = "_altaVideo_arg0-395188820";
        java.lang.String _altaVideo_arg1 = "_altaVideo_arg1-200090966";
        java.lang.String _altaVideo_arg2 = "_altaVideo_arg2943571170";
        long _altaVideo_arg3 = 5256502063798881868l;
        java.lang.String _altaVideo_arg4 = "_altaVideo_arg4-1940899756";
        java.lang.String _altaVideo_arg5 = "_altaVideo_arg51978982094";
        javax.xml.datatype.XMLGregorianCalendar _altaVideo_arg6 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-11-19T12:41:13.536-03:00");
        boolean _altaVideo_arg7 = true;
        port.altaVideo(_altaVideo_arg0, _altaVideo_arg1, _altaVideo_arg2, _altaVideo_arg3, _altaVideo_arg4, _altaVideo_arg5, _altaVideo_arg6, _altaVideo_arg7);


        }
        {
        System.out.println("Invoking getListaDtVideo...");
        java.lang.String _getListaDtVideo_arg0 = "_getListaDtVideo_arg0-1557824739";
        servicios.DtPaquete _getListaDtVideo__return = port.getListaDtVideo(_getListaDtVideo_arg0);
        System.out.println("getListaDtVideo.result=" + _getListaDtVideo__return);


        }
        {
        System.out.println("Invoking existeVideo...");
        java.lang.String _existeVideo_arg0 = "_existeVideo_arg0-1237290116";
        java.lang.String _existeVideo_arg1 = "_existeVideo_arg1202422660";
        boolean _existeVideo__return = port.existeVideo(_existeVideo_arg0, _existeVideo_arg1);
        System.out.println("existeVideo.result=" + _existeVideo__return);


        }
        {
        System.out.println("Invoking getDtUsuario...");
        java.lang.String _getDtUsuario_arg0 = "_getDtUsuario_arg0-575587997";
        servicios.DtPaquete _getDtUsuario__return = port.getDtUsuario(_getDtUsuario_arg0);
        System.out.println("getDtUsuario.result=" + _getDtUsuario__return);


        }
        {
        System.out.println("Invoking prueba...");
        java.lang.String _prueba_arg0 = "_prueba_arg0709024201";
        java.lang.String _prueba__return = port.prueba(_prueba_arg0);
        System.out.println("prueba.result=" + _prueba__return);


        }
        {
        System.out.println("Invoking consultaDeCategoria...");
        java.lang.String _consultaDeCategoria_arg0 = "_consultaDeCategoria_arg0-955559856";
        servicios.DtPaquete _consultaDeCategoria__return = port.consultaDeCategoria(_consultaDeCategoria_arg0);
        System.out.println("consultaDeCategoria.result=" + _consultaDeCategoria__return);


        }
        {
        System.out.println("Invoking checkLogin...");
        java.lang.String _checkLogin_arg0 = "_checkLogin_arg0714321564";
        java.lang.String _checkLogin_arg1 = "_checkLogin_arg1257315698";
        boolean _checkLogin__return = port.checkLogin(_checkLogin_arg0, _checkLogin_arg1);
        System.out.println("checkLogin.result=" + _checkLogin__return);


        }
        {
        System.out.println("Invoking getSeguidos...");
        java.lang.String _getSeguidos_arg0 = "_getSeguidos_arg0-1391399371";
        servicios.DtPaquete _getSeguidos__return = port.getSeguidos(_getSeguidos_arg0);
        System.out.println("getSeguidos.result=" + _getSeguidos__return);


        }
        {
        System.out.println("Invoking listarDtVideosDuenosLista...");
        java.lang.String _listarDtVideosDuenosLista_arg0 = "_listarDtVideosDuenosLista_arg0-1487315123";
        java.lang.String _listarDtVideosDuenosLista_arg1 = "_listarDtVideosDuenosLista_arg1463175695";
        boolean _listarDtVideosDuenosLista_arg2 = true;
        servicios.DtPaquete _listarDtVideosDuenosLista__return = port.listarDtVideosDuenosLista(_listarDtVideosDuenosLista_arg0, _listarDtVideosDuenosLista_arg1, _listarDtVideosDuenosLista_arg2);
        System.out.println("listarDtVideosDuenosLista.result=" + _listarDtVideosDuenosLista__return);


        }
        {
        System.out.println("Invoking modificarValoracion...");
        boolean _modificarValoracion_arg0 = false;
        java.lang.String _modificarValoracion_arg1 = "_modificarValoracion_arg1-1657246513";
        java.lang.String _modificarValoracion_arg2 = "_modificarValoracion_arg2-1437348286";
        java.lang.String _modificarValoracion_arg3 = "_modificarValoracion_arg3-332412389";
        port.modificarValoracion(_modificarValoracion_arg0, _modificarValoracion_arg1, _modificarValoracion_arg2, _modificarValoracion_arg3);


        }
        {
        System.out.println("Invoking getDtDefecto...");
        java.lang.String _getDtDefecto_arg0 = "_getDtDefecto_arg01371468182";
        java.lang.String _getDtDefecto_arg1 = "_getDtDefecto_arg11931400679";
        servicios.DtPaquete _getDtDefecto__return = port.getDtDefecto(_getDtDefecto_arg0, _getDtDefecto_arg1);
        System.out.println("getDtDefecto.result=" + _getDtDefecto__return);


        }
        {
        System.out.println("Invoking yaCalificado...");
        java.lang.String _yaCalificado_arg0 = "_yaCalificado_arg0-922243517";
        boolean _yaCalificado_arg1 = true;
        java.lang.String _yaCalificado_arg2 = "_yaCalificado_arg2836813627";
        java.lang.String _yaCalificado_arg3 = "_yaCalificado_arg31812911728";
        boolean _yaCalificado__return = port.yaCalificado(_yaCalificado_arg0, _yaCalificado_arg1, _yaCalificado_arg2, _yaCalificado_arg3);
        System.out.println("yaCalificado.result=" + _yaCalificado__return);


        }
        {
        System.out.println("Invoking guardarCambios...");
        java.lang.String _guardarCambios_arg0 = "_guardarCambios_arg0-1900027823";
        java.lang.String _guardarCambios_arg1 = "_guardarCambios_arg1-931060332";
        boolean _guardarCambios_arg2 = true;
        port.guardarCambios(_guardarCambios_arg0, _guardarCambios_arg1, _guardarCambios_arg2);


        }
        {
        System.out.println("Invoking dejarSeguir...");
        java.lang.String _dejarSeguir_arg0 = "_dejarSeguir_arg01264067684";
        java.lang.String _dejarSeguir_arg1 = "_dejarSeguir_arg12142202529";
        port.dejarSeguir(_dejarSeguir_arg0, _dejarSeguir_arg1);


        }
        {
        System.out.println("Invoking getDt...");
        int _getDt_arg0 = -1049316910;
        servicios.DtPaquete _getDt__return = port.getDt(_getDt_arg0);
        System.out.println("getDt.result=" + _getDt__return);


        }
        {
        System.out.println("Invoking getSeguidores...");
        java.lang.String _getSeguidores_arg0 = "_getSeguidores_arg0259478235";
        servicios.DtPaquete _getSeguidores__return = port.getSeguidores(_getSeguidores_arg0);
        System.out.println("getSeguidores.result=" + _getSeguidores__return);


        }
        {
        System.out.println("Invoking isSeguidor...");
        java.lang.String _isSeguidor_arg0 = "_isSeguidor_arg01871146091";
        java.lang.String _isSeguidor_arg1 = "_isSeguidor_arg11602788447";
        boolean _isSeguidor__return = port.isSeguidor(_isSeguidor_arg0, _isSeguidor_arg1);
        System.out.println("isSeguidor.result=" + _isSeguidor__return);


        }
        {
        System.out.println("Invoking quitarVideoLista...");
        java.lang.String _quitarVideoLista_arg0 = "_quitarVideoLista_arg01588726556";
        java.lang.String _quitarVideoLista_arg1 = "_quitarVideoLista_arg1-606285073";
        java.lang.String _quitarVideoLista_arg2 = "_quitarVideoLista_arg2-1325890635";
        java.lang.String _quitarVideoLista_arg3 = "_quitarVideoLista_arg3368098546";
        boolean _quitarVideoLista_arg4 = false;
        port.quitarVideoLista(_quitarVideoLista_arg0, _quitarVideoLista_arg1, _quitarVideoLista_arg2, _quitarVideoLista_arg3, _quitarVideoLista_arg4);


        }
        {
        System.out.println("Invoking getDtListasDefectoUsuario...");
        java.lang.String _getDtListasDefectoUsuario_arg0 = "_getDtListasDefectoUsuario_arg01778399918";
        servicios.DtPaquete _getDtListasDefectoUsuario__return = port.getDtListasDefectoUsuario(_getDtListasDefectoUsuario_arg0);
        System.out.println("getDtListasDefectoUsuario.result=" + _getDtListasDefectoUsuario__return);


        }
        {
        System.out.println("Invoking listarListasParticularUsuario...");
        java.lang.String _listarListasParticularUsuario_arg0 = "_listarListasParticularUsuario_arg0-2038865144";
        servicios.DtPaquete _listarListasParticularUsuario__return = port.listarListasParticularUsuario(_listarListasParticularUsuario_arg0);
        System.out.println("listarListasParticularUsuario.result=" + _listarListasParticularUsuario__return);


        }
        {
        System.out.println("Invoking busquedaLista...");
        java.lang.String _busquedaLista_arg0 = "_busquedaLista_arg0-2081887356";
        int _busquedaLista_arg1 = -584200923;
        servicios.DtPaquete _busquedaLista__return = port.busquedaLista(_busquedaLista_arg0, _busquedaLista_arg1);
        System.out.println("busquedaLista.result=" + _busquedaLista__return);


        }
        {
        System.out.println("Invoking listarTodosLosVideos...");
        java.lang.String _listarTodosLosVideos_arg0 = "_listarTodosLosVideos_arg0-1164941601";
        servicios.DtPaquete _listarTodosLosVideos__return = port.listarTodosLosVideos(_listarTodosLosVideos_arg0);
        System.out.println("listarTodosLosVideos.result=" + _listarTodosLosVideos__return);


        }
        {
        System.out.println("Invoking historialVideo...");
        int _historialVideo_arg0 = 1656307484;
        java.lang.String _historialVideo_arg1 = "_historialVideo_arg11634136769";
        try {
            servicios.DtPaquete _historialVideo__return = port.historialVideo(_historialVideo_arg0, _historialVideo_arg1);
            System.out.println("historialVideo.result=" + _historialVideo__return);

        } catch (NotFoundException_Exception e) {
            System.out.println("Expected exception: NotFoundException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking comentarVideo...");
        java.lang.String _comentarVideo_arg0 = "_comentarVideo_arg0-1565408157";
        javax.xml.datatype.XMLGregorianCalendar _comentarVideo_arg1 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-11-19T12:41:13.548-03:00");
        java.lang.String _comentarVideo_arg2 = "_comentarVideo_arg2-706627578";
        java.lang.String _comentarVideo_arg3 = "_comentarVideo_arg31562399270";
        java.lang.String _comentarVideo_arg4 = "_comentarVideo_arg4750851294";
        port.comentarVideo(_comentarVideo_arg0, _comentarVideo_arg1, _comentarVideo_arg2, _comentarVideo_arg3, _comentarVideo_arg4);


        }
        {
        System.out.println("Invoking existeCorreo...");
        java.lang.String _existeCorreo_arg0 = "_existeCorreo_arg066084309";
        boolean _existeCorreo__return = port.existeCorreo(_existeCorreo_arg0);
        System.out.println("existeCorreo.result=" + _existeCorreo__return);


        }
        {
        System.out.println("Invoking prueba2...");
        java.lang.String _prueba2__return = port.prueba2();
        System.out.println("prueba2.result=" + _prueba2__return);


        }
        {
        System.out.println("Invoking modificarUsuario...");
        java.lang.String _modificarUsuario_arg0 = "_modificarUsuario_arg0-2036537335";
        servicios.DtUniversal _modificarUsuario_arg1 = null;
        byte[] _modificarUsuario_imagen = new byte[] {};
        try {
            port.modificarUsuario(_modificarUsuario_arg0, _modificarUsuario_arg1, _modificarUsuario_imagen);

        } catch (NotFoundException_Exception e) {
            System.out.println("Expected exception: NotFoundException has occurred.");
            System.out.println(e.toString());
        } catch (DuplicateClassException_Exception e) {
            System.out.println("Expected exception: DuplicateClassException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking responderComentario...");
        java.lang.String _responderComentario_arg0 = "_responderComentario_arg0-312333646";
        javax.xml.datatype.XMLGregorianCalendar _responderComentario_arg1 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-11-19T12:41:13.551-03:00");
        java.lang.String _responderComentario_arg2 = "_responderComentario_arg2-29617188";
        java.lang.String _responderComentario_arg3 = "_responderComentario_arg31654654749";
        java.lang.String _responderComentario_arg4 = "_responderComentario_arg4-1798105578";
        int _responderComentario_arg5 = -1008364619;
        port.responderComentario(_responderComentario_arg0, _responderComentario_arg1, _responderComentario_arg2, _responderComentario_arg3, _responderComentario_arg4, _responderComentario_arg5);


        }
        {
        System.out.println("Invoking getDtListasParticularesUsuario...");
        java.lang.String _getDtListasParticularesUsuario_arg0 = "_getDtListasParticularesUsuario_arg01362819597";
        servicios.DtPaquete _getDtListasParticularesUsuario__return = port.getDtListasParticularesUsuario(_getDtListasParticularesUsuario_arg0);
        System.out.println("getDtListasParticularesUsuario.result=" + _getDtListasParticularesUsuario__return);


        }
        {
        System.out.println("Invoking agregarVideoLista...");
        java.lang.String _agregarVideoLista_arg0 = "_agregarVideoLista_arg0181342600";
        java.lang.String _agregarVideoLista_arg1 = "_agregarVideoLista_arg1703343811";
        java.lang.String _agregarVideoLista_arg2 = "_agregarVideoLista_arg2-415602206";
        java.lang.String _agregarVideoLista_arg3 = "_agregarVideoLista_arg3-293312809";
        boolean _agregarVideoLista_arg4 = true;
        try {
            port.agregarVideoLista(_agregarVideoLista_arg0, _agregarVideoLista_arg1, _agregarVideoLista_arg2, _agregarVideoLista_arg3, _agregarVideoLista_arg4);

        } catch (InvalidDataException_Exception e) {
            System.out.println("Expected exception: InvalidDataException has occurred.");
            System.out.println(e.toString());
        } catch (DuplicateClassException_Exception e) {
            System.out.println("Expected exception: DuplicateClassException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
