package complejoservidor.publicar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-10-23T17:06:18.821-03:00
 * Generated source version: 3.2.0
 * 
 */
@WebServiceClient(name = "WebServicesService", 
                  wsdlLocation = "http://localhost:9128/webservices?wsdl",
                  targetNamespace = "http://publicar.complejoservidor/") 
public class WebServicesService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://publicar.complejoservidor/", "WebServicesService");
    public final static QName WebServicesPort = new QName("http://publicar.complejoservidor/", "WebServicesPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9128/webservices?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WebServicesService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9128/webservices?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WebServicesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WebServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServicesService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WebServicesService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WebServicesService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WebServicesService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WebServices
     */
    @WebEndpoint(name = "WebServicesPort")
    public WebServices getWebServicesPort() {
        return super.getPort(WebServicesPort, WebServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServices
     */
    @WebEndpoint(name = "WebServicesPort")
    public WebServices getWebServicesPort(WebServiceFeature... features) {
        return super.getPort(WebServicesPort, WebServices.class, features);
    }

}
