
package complejoservidor.publicar;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-11-10T10:29:59.629-03:00
 * Generated source version: 3.2.6
 */

@WebFault(name = "IOException", targetNamespace = "http://publicar.complejoservidor/")
public class IOException_Exception extends Exception {
    
    private complejoservidor.publicar.IOException ioException;

    public IOException_Exception() {
        super();
    }
    
    public IOException_Exception(String message) {
        super(message);
    }
    
    public IOException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

	public IOException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public IOException_Exception(String message, complejoservidor.publicar.IOException ioException) {
        super(message);
        this.ioException = ioException;
    }

    public IOException_Exception(String message, complejoservidor.publicar.IOException ioException, java.lang.Throwable cause) {
        super(message, cause);
        this.ioException = ioException;
    }

	public IOException_Exception(String message, complejoservidor.publicar.IOException ioException, Throwable cause) {
        super(message, cause);
        this.ioException = ioException;
    }

    public complejoservidor.publicar.IOException getFaultInfo() {
        return this.ioException;
    }
}
