
package complejoservidor.publicar;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-10-23T17:06:18.752-03:00
 * Generated source version: 3.2.0
 * 
 */
public final class WebServices_WebServicesPort_Client {

    private static final QName SERVICE_NAME = new QName("http://publicar.complejoservidor/", "WebServicesService");

    private WebServices_WebServicesPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WebServicesService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WebServicesService ss = new WebServicesService(wsdlURL, SERVICE_NAME);
        WebServices port = ss.getWebServicesPort();  
        
        {
        System.out.println("Invoking obtenerApellido...");
        complejoservidor.publicar.DataPersona _obtenerApellido_arg0 = new complejoservidor.publicar.DataPersona();
        _obtenerApellido_arg0.setNombre("Nombre-1092016909");
        _obtenerApellido_arg0.setApellido("Apellido-523898299");
        _obtenerApellido_arg0.setImagen("Imagen-292357847");
        java.lang.String _obtenerApellido__return = port.obtenerApellido(_obtenerApellido_arg0);
        System.out.println("obtenerApellido.result=" + _obtenerApellido__return);


        }
        {
        System.out.println("Invoking getFile...");
        java.lang.String _getFile_fileName = "_getFile_fileName-531146844";
        try {
            byte[] _getFile__return = port.getFile(_getFile_fileName);
            System.out.println("getFile.result=" + _getFile__return);

        } catch (IOException_Exception e) { 
            System.out.println("Expected exception: IOException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking obtenerConvocados...");
        java.lang.String _obtenerConvocados_arg0 = "_obtenerConvocados_arg0-1347598986";
        complejoservidor.publicar.DataMaestro _obtenerConvocados__return = port.obtenerConvocados(_obtenerConvocados_arg0);
        System.out.println("obtenerConvocados.result=" + _obtenerConvocados__return);


        }

        System.exit(0);
    }

}
