package complejoservidor.publicar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-11-10T10:29:59.663-03:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://publicar.complejoservidor/", name = "WebServices")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface WebServices {

    @WebMethod
    @Action(input = "http://publicar.complejoservidor/WebServices/obtenerApellidoRequest", output = "http://publicar.complejoservidor/WebServices/obtenerApellidoResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.complejoservidor/", partName = "return")
    public java.lang.String obtenerApellido(
        @WebParam(partName = "arg0", name = "arg0")
        DataPersona arg0
    );

    @WebMethod
    @Action(input = "http://publicar.complejoservidor/WebServices/getFileRequest", output = "http://publicar.complejoservidor/WebServices/getFileResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://publicar.complejoservidor/WebServices/getFile/Fault/IOException")})
    @WebResult(name = "return", targetNamespace = "http://publicar.complejoservidor/", partName = "return")
    public byte[] getFile(
        @WebParam(partName = "fileName", name = "fileName")
        java.lang.String fileName
    ) throws IOException_Exception;

    @WebMethod
    @Action(input = "http://publicar.complejoservidor/WebServices/obtenerConvocadosRequest", output = "http://publicar.complejoservidor/WebServices/obtenerConvocadosResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.complejoservidor/", partName = "return")
    public DataMaestro obtenerConvocados(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );
}
