/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.4
 * Generated at: 2018-10-15 14:42:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.jasper.tagplugins.jstl.core.Out;
import javax.xml.ws.Response;
import java.io.Writer;
import datatypes.DtVideo;
import datatypes.DtComentario;
import datatypes.DtUsuario;
import java.util.Map;
import java.util.List;
import java.text.DateFormat;
import java.util.List;
import java.text.ParseException;
import java.text.SimpleDateFormat;

public final class consulta_005fvideo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

 DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1539604840000L));
    _jspx_dependants.put("jar:file:/ens/home01/f/francisco.crocamo/Desktop/apache-tomcat-8.5.4/webapps/UyTube/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153395882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("datatypes.DtUsuario");
    _jspx_imports_classes.add("datatypes.DtVideo");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("javax.xml.ws.Response");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.io.Writer");
    _jspx_imports_classes.add("datatypes.DtComentario");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.text.ParseException");
    _jspx_imports_classes.add("org.apache.jasper.tagplugins.jstl.core.Out");
    _jspx_imports_classes.add("java.text.DateFormat");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/extras/head.jsp", out, false);
      out.write("\n");
      out.write("\t<title>UyTube - Consulta Video</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"page\">\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/extras/header.jsp", out, false);
      out.write("\n");
      out.write("\t\t<div class=\"contenedor\">\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/extras/sidebar.jsp", out, false);
      out.write("\n");
      out.write("\t\t<div class= \"contenido\">\n");
      out.write("\t\t\t ");
 DtVideo vid = (DtVideo) request.getAttribute("DT_VIDEO"); 
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<h1>");
      out.print( vid.nombre );
      out.write("</h1>\n");
      out.write("\t\t\t\t <br><br>\n");
      out.write("\t\t\t<iframe width=\"700\" height=\"465\"\n");
      out.write("\t\t\t\tsrc=\"");
      out.print( vid.urlWatchtFormat() );
      out.write(" \">\n");
      out.write("\n");
      out.write("\t\t\t</iframe>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t\t<h4>Canal:</h4> ");
      out.print( vid.usuario );
      out.write("\n");
      out.write("\t\t\t\t <br>\n");
      out.write("\t\t\t\t");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t<h4>Fecha:</h4> ");
      out.print( format.format(vid.fecha) );
      out.write("\n");
      out.write("\t\t\t\t <br>\n");
      out.write("\n");
      out.write("\t\t\t\t<h4>Duracion:</h4> ");
      out.print( vid.duracionPrintFormat() );
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t <br>\n");
      out.write("\n");
      out.write("\t\t\t\t<h4>Categoria:</h4> ");
      out.print( vid.categoria );
      out.write("\n");
      out.write("\t\t\t\t <br>\n");
      out.write("\t\t\t\t<h4>URL:</h4> ");
      out.print(vid.urlVideo);
      out.write("\n");
      out.write("\t\t\t\t <br>\n");
      out.write("\t\t\t\t<h4>Descripcion:</h4> ");
      out.print( vid.descripcion );
      out.write("\n");
      out.write("\t\t\t\t <br><br>\n");
      out.write("\t\t\t\t<h5>Me gusta:</h5> ");
      out.print( vid.getCantidadCalificacionesPositivas());
      out.write("\n");
      out.write("\t\t\t\t");
DtUsuario d = (DtUsuario)request.getSession().getAttribute("USUARIO_LOGEADO");

				if(d != null){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t<form action=\"ConsultaVideo\" method=\"POST\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"ACCION\" value=\"VALORAR_POSITIVO\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"1\" name=\"VIDEO_ID\" value= \"");
      out.print( vid.idVideo );
      out.write("\" >\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\">Valorar</button>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\n");
      out.write("\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t<br><br>\n");
      out.write("\t\t\t\t");
 List<String> positivos = vid.getCalificacionesPositivas();
				if(d != null && vid.usuario == d.nick){
					for(String user: positivos){
      out.write("\n");
      out.write("\t\t\t\t\t\t");
      out.print( user );
      out.write("\n");
      out.write("\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t");
}
				}
				
      out.write("\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\n");
      out.write("\t\t\t\t<h5>No me gusta:</h5> ");
      out.print( vid.getCantidadCalificacionesNegativas());
      out.write("\n");
      out.write("\t\t\t\t");
if(d != null){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t<form action=\"ConsultaVideo\" method=\"POST\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"ACCION\" value=\"VALORAR_NEGATIVO\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"1\" name=\"VIDEO_ID\" value= \"");
      out.print( vid.idVideo );
      out.write("\" >\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\">Valorar</button>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\n");
      out.write("\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t<br><br>\n");
      out.write("\t\t\t\t");
 List<String> negativos = vid.getCalificacionesNegativas();
				if(d != null && vid.usuario == d.nick){
					for(String user: negativos){
      out.write("\n");
      out.write("\t\t\t\t\t\t");
      out.print( user );
      out.write("\n");
      out.write("\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t");
}
				}
				
      out.write("\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\n");
      out.write("\t\t\t\t<h4>Comentarios:</h4>\n");
      out.write("\n");
      out.write("\t\t\t\t");
if(vid.comentarios.isEmpty()){ 
      out.write("\n");
      out.write("\t\t\t\tNo hay comentarios\n");
      out.write("\t\t\t\t");
} 
      out.write("\n");
      out.write("\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('	');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "comentarios.jsp", out, false);
      out.write("\n");
      out.write("\t\t<br>\n");
      out.write("\t\t");
if(d!=null){ 
      out.write("\n");
      out.write("\t\t\t<form action=\"ConsultaVideo\" method=\"POST\">\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"ACCION\" value=\"COMENTAR\">\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"COMENTARIO\">\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"1\" name=\"VIDEO_ID\" value= \"");
      out.print( vid.idVideo );
      out.write("\" >\n");
      out.write("\t\t\t\t<button type=\"submit\">Comentar</button>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t");
 } 
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/extras/script.jsp", out, false);
      out.write("\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/pages/consulta_video.jsp(102,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("comentarios");
    // /WEB-INF/pages/consulta_video.jsp(102,2) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/pages/consulta_video.jsp(102,2) '${DT_VIDEO.comentarios}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${DT_VIDEO.comentarios}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/pages/consulta_video.jsp(102,2) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setScope("request");
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }
}
