
package servicios;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-11-06T22:22:06.946-03:00
 * Generated source version: 3.2.6
 */

@WebFault(name = "Exception", targetNamespace = "http://servicios/")
public class Exception_Exception extends java.lang.Exception {

    private servicios.Exception exception;

    public Exception_Exception() {
        super();
    }

    public Exception_Exception(String message) {
        super(message);
    }

    public Exception_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, servicios.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, servicios.Exception exception, java.lang.Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public servicios.Exception getFaultInfo() {
        return this.exception;
    }
}
