
package servicios;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.2.6
<<<<<<< HEAD
 * 2018-11-10T17:15:29.273-03:00
=======
 * 2018-11-10T13:54:07.567-03:00
>>>>>>> WS-fran
 * Generated source version: 3.2.6
 *
 */
public final class Publicador_PublicadorPort_Client {

    private static final QName SERVICE_NAME = new QName("http://servicios/", "PublicadorService");

    private Publicador_PublicadorPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PublicadorService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        PublicadorService ss = new PublicadorService(wsdlURL, SERVICE_NAME);
        Publicador port = ss.getPublicadorPort();

        {
        System.out.println("Invoking prueba...");
<<<<<<< HEAD
        java.lang.String _prueba_arg0 = "_prueba_arg01032585424";
=======
        java.lang.String _prueba_arg0 = "_prueba_arg0514412291";
>>>>>>> WS-fran
        java.lang.String _prueba__return = port.prueba(_prueba_arg0);
        System.out.println("prueba.result=" + _prueba__return);


        }
        {
<<<<<<< HEAD
        System.out.println("Invoking consultaDeCategoria...");
        java.lang.String _consultaDeCategoria_arg0 = "_consultaDeCategoria_arg0-1882084098";
=======
        System.out.println("Invoking busquedaGeneral...");
        java.lang.String _busquedaGeneral_arg0 = "_busquedaGeneral_arg0-1191385962";
        int _busquedaGeneral_arg1 = -933168350;
        servicios.DtPaquete _busquedaGeneral__return = port.busquedaGeneral(_busquedaGeneral_arg0, _busquedaGeneral_arg1);
        System.out.println("busquedaGeneral.result=" + _busquedaGeneral__return);


        }
        {
        System.out.println("Invoking getListaPublicoDtVideo...");
        servicios.DtPaquete _getListaPublicoDtVideo__return = port.getListaPublicoDtVideo();
        System.out.println("getListaPublicoDtVideo.result=" + _getListaPublicoDtVideo__return);


        }
        {
        System.out.println("Invoking consultaDeCategoria...");
        java.lang.String _consultaDeCategoria_arg0 = "_consultaDeCategoria_arg0-2004397453";
>>>>>>> WS-fran
        servicios.DtPaquete _consultaDeCategoria__return = port.consultaDeCategoria(_consultaDeCategoria_arg0);
        System.out.println("consultaDeCategoria.result=" + _consultaDeCategoria__return);


        }
        {
        System.out.println("Invoking checkLogin...");
<<<<<<< HEAD
        java.lang.String _checkLogin_arg0 = "_checkLogin_arg01146671591";
        java.lang.String _checkLogin_arg1 = "_checkLogin_arg1-41750626";
=======
        java.lang.String _checkLogin_arg0 = "_checkLogin_arg0888084761";
        java.lang.String _checkLogin_arg1 = "_checkLogin_arg11624948958";
>>>>>>> WS-fran
        boolean _checkLogin__return = port.checkLogin(_checkLogin_arg0, _checkLogin_arg1);
        System.out.println("checkLogin.result=" + _checkLogin__return);


        }
        {
<<<<<<< HEAD
        System.out.println("Invoking getDtListasPrivadasUsuario...");
        java.lang.String _getDtListasPrivadasUsuario_arg0 = "_getDtListasPrivadasUsuario_arg0321895653";
        servicios.DtPaquete _getDtListasPrivadasUsuario__return = port.getDtListasPrivadasUsuario(_getDtListasPrivadasUsuario_arg0);
        System.out.println("getDtListasPrivadasUsuario.result=" + _getDtListasPrivadasUsuario__return);
=======
        System.out.println("Invoking comentarVideo...");
        java.lang.String _comentarVideo_arg0 = "_comentarVideo_arg0-1198483501";
        javax.xml.datatype.XMLGregorianCalendar _comentarVideo_arg1 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-11-10T13:54:07.611-03:00");
        java.lang.String _comentarVideo_arg2 = "_comentarVideo_arg2568511639";
        java.lang.String _comentarVideo_arg3 = "_comentarVideo_arg31649484360";
        java.lang.String _comentarVideo_arg4 = "_comentarVideo_arg4-1165368772";
        port.comentarVideo(_comentarVideo_arg0, _comentarVideo_arg1, _comentarVideo_arg2, _comentarVideo_arg3, _comentarVideo_arg4);


        }
        {
        System.out.println("Invoking getDtVideo...");
        int _getDtVideo_arg0 = 1923968565;
        servicios.DtPaquete _getDtVideo__return = port.getDtVideo(_getDtVideo_arg0);
        System.out.println("getDtVideo.result=" + _getDtVideo__return);
>>>>>>> WS-fran


        }
        {
<<<<<<< HEAD
        System.out.println("Invoking getDtVideo...");
        int _getDtVideo_arg0 = 962740644;
        servicios.DtPaquete _getDtVideo__return = port.getDtVideo(_getDtVideo_arg0);
        System.out.println("getDtVideo.result=" + _getDtVideo__return);
=======
        System.out.println("Invoking valorarVideo...");
        java.lang.String _valorarVideo_arg0 = "_valorarVideo_arg0157020034";
        boolean _valorarVideo_arg1 = false;
        java.lang.String _valorarVideo_arg2 = "_valorarVideo_arg2-587649115";
        java.lang.String _valorarVideo_arg3 = "_valorarVideo_arg3-1149551875";
        port.valorarVideo(_valorarVideo_arg0, _valorarVideo_arg1, _valorarVideo_arg2, _valorarVideo_arg3);
>>>>>>> WS-fran


        }
        {
        System.out.println("Invoking modificarValoracion...");
        boolean _modificarValoracion_arg0 = false;
<<<<<<< HEAD
        java.lang.String _modificarValoracion_arg1 = "_modificarValoracion_arg1-451560917";
        java.lang.String _modificarValoracion_arg2 = "_modificarValoracion_arg2-854055119";
        java.lang.String _modificarValoracion_arg3 = "_modificarValoracion_arg3-678725446";
=======
        java.lang.String _modificarValoracion_arg1 = "_modificarValoracion_arg1552282713";
        java.lang.String _modificarValoracion_arg2 = "_modificarValoracion_arg2307972615";
        java.lang.String _modificarValoracion_arg3 = "_modificarValoracion_arg3-604972670";
>>>>>>> WS-fran
        port.modificarValoracion(_modificarValoracion_arg0, _modificarValoracion_arg1, _modificarValoracion_arg2, _modificarValoracion_arg3);


        }
        {
        System.out.println("Invoking listarCategorias...");
        servicios.DtPaquete _listarCategorias__return = port.listarCategorias();
        System.out.println("listarCategorias.result=" + _listarCategorias__return);


        }
        {
<<<<<<< HEAD
        System.out.println("Invoking getDtDefecto...");
        java.lang.String _getDtDefecto_arg0 = "_getDtDefecto_arg0-586783451";
        java.lang.String _getDtDefecto_arg1 = "_getDtDefecto_arg1-577703680";
        servicios.DtPaquete _getDtDefecto__return = port.getDtDefecto(_getDtDefecto_arg0, _getDtDefecto_arg1);
        System.out.println("getDtDefecto.result=" + _getDtDefecto__return);


        }
        {
        System.out.println("Invoking yaCalificado...");
        java.lang.String _yaCalificado_arg0 = "_yaCalificado_arg01172921046";
        boolean _yaCalificado_arg1 = false;
        java.lang.String _yaCalificado_arg2 = "_yaCalificado_arg2-662693206";
        java.lang.String _yaCalificado_arg3 = "_yaCalificado_arg3-516196898";
=======
        System.out.println("Invoking yaCalificado...");
        java.lang.String _yaCalificado_arg0 = "_yaCalificado_arg01689345583";
        boolean _yaCalificado_arg1 = true;
        java.lang.String _yaCalificado_arg2 = "_yaCalificado_arg2-1040405860";
        java.lang.String _yaCalificado_arg3 = "_yaCalificado_arg31578280320";
>>>>>>> WS-fran
        boolean _yaCalificado__return = port.yaCalificado(_yaCalificado_arg0, _yaCalificado_arg1, _yaCalificado_arg2, _yaCalificado_arg3);
        System.out.println("yaCalificado.result=" + _yaCalificado__return);


        }
        {
<<<<<<< HEAD
        System.out.println("Invoking getListasPublicas...");
        servicios.DtPaquete _getListasPublicas__return = port.getListasPublicas();
        System.out.println("getListasPublicas.result=" + _getListasPublicas__return);
=======
        System.out.println("Invoking altaUsuario...");
        java.lang.String _altaUsuario_arg0 = "_altaUsuario_arg0-1990458626";
        java.lang.String _altaUsuario_arg1 = "_altaUsuario_arg1-1824469002";
        java.lang.String _altaUsuario_arg2 = "_altaUsuario_arg2-1356017021";
        java.lang.String _altaUsuario_arg3 = "_altaUsuario_arg3-1955941096";
        javax.xml.datatype.XMLGregorianCalendar _altaUsuario_arg4 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-11-10T13:54:07.619-03:00");
        byte[] _altaUsuario_arg5 = new byte[] {};
        java.lang.String _altaUsuario_arg6 = "_altaUsuario_arg6-465369390";
        java.lang.String _altaUsuario_arg7 = "_altaUsuario_arg7-133531163";
        java.lang.String _altaUsuario_arg8 = "_altaUsuario_arg8-1462607989";
        boolean _altaUsuario_arg9 = false;
        java.lang.String _altaUsuario_arg10 = "_altaUsuario_arg10-1947805949";
        port.altaUsuario(_altaUsuario_arg0, _altaUsuario_arg1, _altaUsuario_arg2, _altaUsuario_arg3, _altaUsuario_arg4, _altaUsuario_arg5, _altaUsuario_arg6, _altaUsuario_arg7, _altaUsuario_arg8, _altaUsuario_arg9, _altaUsuario_arg10);
>>>>>>> WS-fran


        }
        {
<<<<<<< HEAD
        System.out.println("Invoking getDt...");
        int _getDt_arg0 = -1342730480;
        servicios.DtPaquete _getDt__return = port.getDt(_getDt_arg0);
        System.out.println("getDt.result=" + _getDt__return);
=======
        System.out.println("Invoking busquedaCanales...");
        java.lang.String _busquedaCanales_arg0 = "_busquedaCanales_arg0-1694726206";
        int _busquedaCanales_arg1 = 1181424210;
        servicios.DtPaquete _busquedaCanales__return = port.busquedaCanales(_busquedaCanales_arg0, _busquedaCanales_arg1);
        System.out.println("busquedaCanales.result=" + _busquedaCanales__return);
>>>>>>> WS-fran


        }
        {
        System.out.println("Invoking responderComentario...");
        java.lang.String _responderComentario_arg0 = "_responderComentario_arg0-593542777";
        javax.xml.datatype.XMLGregorianCalendar _responderComentario_arg1 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-11-10T13:54:07.621-03:00");
        java.lang.String _responderComentario_arg2 = "_responderComentario_arg21357662709";
        java.lang.String _responderComentario_arg3 = "_responderComentario_arg3426726016";
        java.lang.String _responderComentario_arg4 = "_responderComentario_arg4834032014";
        int _responderComentario_arg5 = -2021163952;
        port.responderComentario(_responderComentario_arg0, _responderComentario_arg1, _responderComentario_arg2, _responderComentario_arg3, _responderComentario_arg4, _responderComentario_arg5);


        }
        {
        System.out.println("Invoking busquedaVideo...");
<<<<<<< HEAD
        java.lang.String _busquedaVideo_arg0 = "_busquedaVideo_arg0-1774858434";
        int _busquedaVideo_arg1 = 309866098;
=======
        java.lang.String _busquedaVideo_arg0 = "_busquedaVideo_arg0-334668663";
        int _busquedaVideo_arg1 = -115217723;
>>>>>>> WS-fran
        servicios.DtPaquete _busquedaVideo__return = port.busquedaVideo(_busquedaVideo_arg0, _busquedaVideo_arg1);
        System.out.println("busquedaVideo.result=" + _busquedaVideo__return);


        }
        {
        System.out.println("Invoking cargarDatos...");
        port.cargarDatos();


        }
        {
        System.out.println("Invoking getDtListasDefectoUsuario...");
        java.lang.String _getDtListasDefectoUsuario_arg0 = "_getDtListasDefectoUsuario_arg01165987652";
        servicios.DtPaquete _getDtListasDefectoUsuario__return = port.getDtListasDefectoUsuario(_getDtListasDefectoUsuario_arg0);
        System.out.println("getDtListasDefectoUsuario.result=" + _getDtListasDefectoUsuario__return);


        }
        {
        System.out.println("Invoking busquedaLista...");
        java.lang.String _busquedaLista_arg0 = "_busquedaLista_arg01447565906";
        int _busquedaLista_arg1 = 981597431;
        servicios.DtPaquete _busquedaLista__return = port.busquedaLista(_busquedaLista_arg0, _busquedaLista_arg1);
        System.out.println("busquedaLista.result=" + _busquedaLista__return);


        }
        {
        System.out.println("Invoking busquedaGeneral...");
        java.lang.String _busquedaGeneral_arg0 = "_busquedaGeneral_arg0442310535";
        int _busquedaGeneral_arg1 = -1435389728;
        servicios.DtPaquete _busquedaGeneral__return = port.busquedaGeneral(_busquedaGeneral_arg0, _busquedaGeneral_arg1);
        System.out.println("busquedaGeneral.result=" + _busquedaGeneral__return);


        }
        {
        System.out.println("Invoking getListaPublicoDtVideo...");
        servicios.DtPaquete _getListaPublicoDtVideo__return = port.getListaPublicoDtVideo();
        System.out.println("getListaPublicoDtVideo.result=" + _getListaPublicoDtVideo__return);


        }
        {
        System.out.println("Invoking comentarVideo...");
        java.lang.String _comentarVideo_arg0 = "_comentarVideo_arg0335348655";
        javax.xml.datatype.XMLGregorianCalendar _comentarVideo_arg1 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-11-10T17:15:29.353-03:00");
        java.lang.String _comentarVideo_arg2 = "_comentarVideo_arg21275746200";
        java.lang.String _comentarVideo_arg3 = "_comentarVideo_arg3983567451";
        java.lang.String _comentarVideo_arg4 = "_comentarVideo_arg41192679234";
        port.comentarVideo(_comentarVideo_arg0, _comentarVideo_arg1, _comentarVideo_arg2, _comentarVideo_arg3, _comentarVideo_arg4);


        }
        {
        System.out.println("Invoking valorarVideo...");
        java.lang.String _valorarVideo_arg0 = "_valorarVideo_arg0-1499609477";
        boolean _valorarVideo_arg1 = true;
        java.lang.String _valorarVideo_arg2 = "_valorarVideo_arg2-1112450801";
        java.lang.String _valorarVideo_arg3 = "_valorarVideo_arg3-2063045934";
        port.valorarVideo(_valorarVideo_arg0, _valorarVideo_arg1, _valorarVideo_arg2, _valorarVideo_arg3);


        }
        {
        System.out.println("Invoking prueba2...");
        java.lang.String _prueba2__return = port.prueba2();
        System.out.println("prueba2.result=" + _prueba2__return);


        }
        {
        System.out.println("Invoking altaUsuario...");
        java.lang.String _altaUsuario_arg0 = "_altaUsuario_arg028716082";
        java.lang.String _altaUsuario_arg1 = "_altaUsuario_arg1-359583510";
        java.lang.String _altaUsuario_arg2 = "_altaUsuario_arg21948972530";
        java.lang.String _altaUsuario_arg3 = "_altaUsuario_arg3-1786847740";
        javax.xml.datatype.XMLGregorianCalendar _altaUsuario_arg4 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-11-10T17:15:29.357-03:00");
        byte[] _altaUsuario_arg5 = new byte[] {};
        java.lang.String _altaUsuario_arg6 = "_altaUsuario_arg61047421079";
        java.lang.String _altaUsuario_arg7 = "_altaUsuario_arg71417544461";
        java.lang.String _altaUsuario_arg8 = "_altaUsuario_arg8-931526073";
        boolean _altaUsuario_arg9 = true;
        java.lang.String _altaUsuario_arg10 = "_altaUsuario_arg10642622496";
        port.altaUsuario(_altaUsuario_arg0, _altaUsuario_arg1, _altaUsuario_arg2, _altaUsuario_arg3, _altaUsuario_arg4, _altaUsuario_arg5, _altaUsuario_arg6, _altaUsuario_arg7, _altaUsuario_arg8, _altaUsuario_arg9, _altaUsuario_arg10);


        }
        {
        System.out.println("Invoking responderComentario...");
        java.lang.String _responderComentario_arg0 = "_responderComentario_arg0-2115477272";
        javax.xml.datatype.XMLGregorianCalendar _responderComentario_arg1 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-11-10T17:15:29.360-03:00");
        java.lang.String _responderComentario_arg2 = "_responderComentario_arg22033321802";
        java.lang.String _responderComentario_arg3 = "_responderComentario_arg3-774040760";
        java.lang.String _responderComentario_arg4 = "_responderComentario_arg4-812957551";
        int _responderComentario_arg5 = 789411067;
        port.responderComentario(_responderComentario_arg0, _responderComentario_arg1, _responderComentario_arg2, _responderComentario_arg3, _responderComentario_arg4, _responderComentario_arg5);


        }
        {
        System.out.println("Invoking busquedaCanales...");
        java.lang.String _busquedaCanales_arg0 = "_busquedaCanales_arg0-313563275";
        int _busquedaCanales_arg1 = 1383238093;
        servicios.DtPaquete _busquedaCanales__return = port.busquedaCanales(_busquedaCanales_arg0, _busquedaCanales_arg1);
        System.out.println("busquedaCanales.result=" + _busquedaCanales__return);


        }
        {
        System.out.println("Invoking getListaDtVideo...");
<<<<<<< HEAD
        java.lang.String _getListaDtVideo_arg0 = "_getListaDtVideo_arg01365746662";
=======
        java.lang.String _getListaDtVideo_arg0 = "_getListaDtVideo_arg022615722";
>>>>>>> WS-fran
        servicios.DtPaquete _getListaDtVideo__return = port.getListaDtVideo(_getListaDtVideo_arg0);
        System.out.println("getListaDtVideo.result=" + _getListaDtVideo__return);


        }
        {
<<<<<<< HEAD
        System.out.println("Invoking getDtUsuario...");
        java.lang.String _getDtUsuario_arg0 = "_getDtUsuario_arg01830457949";
        servicios.DtPaquete _getDtUsuario__return = port.getDtUsuario(_getDtUsuario_arg0);
        System.out.println("getDtUsuario.result=" + _getDtUsuario__return);


        }
=======
        System.out.println("Invoking busquedaLista...");
        java.lang.String _busquedaLista_arg0 = "_busquedaLista_arg0932090980";
        int _busquedaLista_arg1 = -581709098;
        servicios.DtPaquete _busquedaLista__return = port.busquedaLista(_busquedaLista_arg0, _busquedaLista_arg1);
        System.out.println("busquedaLista.result=" + _busquedaLista__return);


        }
        {
        System.out.println("Invoking getDtUsuario...");
        java.lang.String _getDtUsuario_arg0 = "_getDtUsuario_arg0-1635631739";
        servicios.DtPaquete _getDtUsuario__return = port.getDtUsuario(_getDtUsuario_arg0);
        System.out.println("getDtUsuario.result=" + _getDtUsuario__return);


        }
>>>>>>> WS-fran

        System.exit(0);
    }

}
