/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.4
 * Generated at: 2018-10-15 14:19:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import datatypes.DtUsuario;
import datatypes.DtVideo;
import java.util.List;

public final class listar_005fvideos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("datatypes.DtUsuario");
    _jspx_imports_classes.add("datatypes.DtVideo");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<!-- CUANDO EN EL INDEX SE LISTEN LOS VIDEOS, ESTO SE PUEDE PELAR -->\n");
      out.write("<head>\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/extras/head.jsp", out, false);
      out.write("\n");
      out.write("\t<title>UyTube - Lista de Videos</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"page\">\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/extras/header.jsp", out, false);
      out.write('\n');
      out.write('	');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/extras/sidebar.jsp", out, false);
      out.write("\n");
      out.write("\t\t<div class=\"contenido\">\n");
      out.write("\t\t\t<p>Videos Publicos:</p>\n");
      out.write("\t\t\t<div class=\"highlights\">\n");
      out.write("\t\t\t");

				List<DtVideo> listaVideosPublicos = (List<DtVideo>) request.getAttribute("VIDEOS_PUBLICOS");
				String cast;
				for(DtVideo vp: listaVideosPublicos) { 
				cast = Integer.toString(vp.idVideo);
				
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"detalleClickeableVideo\"onclick=\"document.getElementById('Form");
      out.print(vp.idVideo);
      out.write("').submit();\">\t\n");
      out.write("\t\t\t\t\t<form id=\"Form");
      out.print(vp.idVideo);
      out.write("\" class=\"detClickeableVideo\" action=\"ConsultaVideo\" method=\"GET\">\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" id=\"1\" name=\"VIDEO_ID\" value=\"");
      out.print(cast);
      out.write("\">\n");
      out.write("\t\t\t\t\t\t<img class=\"icon\" width=\"30%\" alt=\"DetalleVideo\" src=\"");
      out.print(vp.urlThumbnail);
      out.write("\">\n");
      out.write("\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t<header>\n");
      out.write("\t\t\t\t\t\t");
      out.print(vp.nombre);
      out.write("\n");
      out.write("\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\tUsuario: ");
      out.print(vp.usuario);
      out.write("\n");
      out.write("\t\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t</form>\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t");

				  }
				
      out.write("\n");
      out.write("\t\t\t</div>\t\n");
      out.write("\t\t\t<p>Videos del usuario:</p>\n");
      out.write("\t\t\t<div class=\"highlights\">\n");
      out.write("\t\t\t\t");

				  DtUsuario d = (DtUsuario)request.getSession().getAttribute("USUARIO_LOGEADO");
								if(d != null){
				
      out.write("\n");
      out.write("\t\t\t\t ");

				   List<DtVideo> listaVideosUsuario = (List<DtVideo>) request.getAttribute("VIDEOS_USUARIO");
				 					String cast2;
				 					for (DtVideo v : listaVideosUsuario) { 
				 						cast2 = Integer.toString(v.idVideo);
				 
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"detalleClickeableVideo\"onclick=\"document.getElementById('Form");
      out.print(v.idVideo);
      out.write("').submit();\">\t\n");
      out.write("\t\t\t\t\t<form id=\"Form");
      out.print(v.idVideo);
      out.write("\" class=\"detClickeableVideo\" action=\"ConsultaVideo\" method=\"GET\">\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" id=\"1\" name=\"VIDEO_ID\" value=\"");
      out.print(cast2);
      out.write("\">\n");
      out.write("\t\t\t\t\t\t<img class=\"icon\" width=\"30%\" alt=\"DetalleVideo\" src=\"");
      out.print(v.urlThumbnail);
      out.write("\">\n");
      out.write("\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t<header>\n");
      out.write("\t\t\t\t\t\t");
      out.print( v.nombre );
      out.write("\n");
      out.write("\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\tUser: ");
      out.print( v.usuario );
      out.write("\n");
      out.write("\t\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t</form>\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t");
 } } 
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/extras/script.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
