/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.4
 * Generated at: 2018-10-15 14:49:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import datatypes.DtUsuario;
import datatypes.DtVideo;
import java.util.List;
import java.text.ParseException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.util.Date;

public final class modificar_005fvideo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("datatypes.DtUsuario");
    _jspx_imports_classes.add("datatypes.DtVideo");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.time.Duration");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.text.ParseException");
    _jspx_imports_classes.add("java.text.DateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/extras/head.jsp", out, false);
      out.write("\n");
      out.write("\t<title>UyTube - Modificar video</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/extras/header.jsp", out, false);
      out.write('\n');
      out.write('	');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/extras/sidebar.jsp", out, false);
      out.write("\n");
      out.write("\t\t<div class=\"contenido\">\n");
      out.write("\t");
 if (request.getAttribute("DUPLICADO") != null) { 
      out.write("\n");
      out.write("\t\t<h1 style=\"color:red\">");
      out.print( request.getAttribute("DUPLICADO") );
      out.write("</h1>\n");
      out.write("\t");
 } else if (request.getAttribute("DURACION") != null) { 
      out.write("\n");
      out.write("\t\t<h1 style=\"color:red\">");
      out.print( request.getAttribute("DURACION") );
      out.write("</h1>\n");
      out.write("\t");
 } else if (request.getAttribute("PRIVACIDAD") != null) {
      out.write("\n");
      out.write("\t\t<h1 style=\"color:red\">");
      out.print( request.getAttribute("PRIVACIDAD") );
      out.write("</h1>\n");
      out.write("\t");
 } 
      out.write('\n');
      out.write('	');
 DtVideo video = (DtVideo) request.getAttribute("VIDEO"); 
      out.write('\n');
      out.write('	');
 String nombreVideo = video.nombre; 
      out.write('\n');
      out.write('	');
 String categoria = video.categoria; 
      out.write('\n');
      out.write('	');
 String descripcion = video.descripcion; 
      out.write('\n');
      out.write('	');

	  String url = video.urlVideo;
	
      out.write('\n');
      out.write('	');

	  String visibilidad = video.visible ? "Publico" : "Privado";
	
      out.write('\n');
      out.write('	');

	  String horas = Long.toString(video.duracion.toHours());
	
      out.write('\n');
      out.write('	');

	  String minutos = Long.toString((video.duracion.getSeconds() % (3600)) / 60);
	
      out.write('\n');
      out.write('	');

	  String segundos = Long.toString(video.duracion.getSeconds() % 60);
	
      out.write('\n');
      out.write('	');

	  DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
		String date = format.format(video.fecha);
	
      out.write("\n");
      out.write("\n");
      out.write("\t<form action=\"ModificarVideo\" method=\"POST\">\n");
      out.write("\t\t<input type=\"hidden\" name=\"oldNombre\" value=\"");
      out.print(video.nombre);
      out.write("\">\n");
      out.write("\t\tNombre del video: <br> <input type=\"text\" name=\"nombreVideo\" value=\"");
      out.print(video.nombre);
      out.write("\">\n");
      out.write("\t\t<br>\n");
      out.write("\t\tCategoria del video: <br>\n");
      out.write("\t\t<select required name=\"categoria\">\n");
      out.write("\t\t<option value=\"");
      out.print(video.categoria);
      out.write('"');
      out.write('>');
      out.print(video.categoria);
      out.write(" </option>\n");
      out.write("\t\t");

		  for (String cat : (String[]) request.getAttribute("CATEGORIAS")) {
		
      out.write("\n");
      out.write("\t\t\t");

			  if (!cat.equals(video.categoria)) {
			
      out.write("\n");
      out.write("\t\t\t\t<option value=\"");
      out.print(cat);
      out.write('"');
      out.write('>');
      out.print(cat);
      out.write(" </option>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t");

			  }
			
      out.write('\n');
      out.write('	');
      out.write('	');

		  }
		
      out.write("\n");
      out.write("\t\t</select>\n");
      out.write("\t\t<br>\n");
      out.write("\t\tDescripción: <br>\n");
      out.write("\t\t<textarea rows=\"5\" cols=\"35\" name=\"descripcionVideo\">");
      out.print(video.descripcion);
      out.write("</textarea>\n");
      out.write("\t\t<br>\n");
      out.write("\t\tURL: <br> <input type=\"text\" name=\"urlVideo\" value=\"");
      out.print(video.urlVideo);
      out.write("\">\n");
      out.write("\t\t<br>\n");
      out.write("\t\tVisibilidad: <br>\n");
      out.write("\t\t<select required name=\"visibilidad\">\n");
      out.write("\t\t\t<option value=\"");
      out.print( visibilidad );
      out.write('"');
      out.write('>');
      out.print( visibilidad );
      out.write(" </option>\n");
      out.write("\t\t\t");
 if (visibilidad.equals("Publico")) { 
      out.write("\n");
      out.write("\t\t\t\t<option value=\"Privado\">Privado</option>\n");
      out.write("\t\t\t");
 } else { 
      out.write("\n");
      out.write("\t\t\t\t<option value=\"Publico\">Publico</option>\n");
      out.write("\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t</select>\n");
      out.write("\t\t<br>\n");
      out.write("\t\tDuracion (H M S): <br> <input type=\"number\" name=\"duracionH\" id=\"hora\" min=\"0\" oninput=\"validity.valid||(value='');\" value=\"");
      out.print( horas );
      out.write("\"required><input type=\"number\" name=\"duracionM\" id=\"minuto\" min=\"0\" oninput=\"validity.valid||(value='');\" value=\"");
      out.print( minutos );
      out.write("\"required><input type=\"number\" id=\"segundo\" min=\"0\" name=\"duracionS\" oninput=\"validity.valid||(value='');\" value=\"");
      out.print( segundos );
      out.write("\"required>*\n");
      out.write("\t\t<br>\n");
      out.write("\t\tFecha: <br> <input type=\"date\" value=\"");
      out.print( date );
      out.write("\" name=\"fecha\" required>*\n");
      out.write("\t\t<input type=\"hidden\" name=\"modificar\"  value=\"\">\n");
      out.write("\t\t<br>\n");
      out.write("\t\t<input type=\"submit\" onclick=\"validate()\" value=\"Modificar datos\">\n");
      out.write("\t\t</div>\n");
      out.write("\t</form>\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
